### PR TITLE
Swift2 - Xcode7b4

### PR DESCRIPTION
**Pull request by mpclarkson**
"&".join has changed to .joinWithSeparator("&")

### CODE REVIEW

**Comment by redox** [comment]
Hi @mpclarkson,

thank you very much for your help. It seems like it's similar to https://github.com/algolia/algoliasearch-client-swift/pull/10, did you try our `swift2` branch?

**Comment by argon** [comment]
@redox it is similar, but it has the latest changes as mentioned in the first comment
#10 gives the following errors
screen shot 2015-08-26 at 22 58 34

**Comment by dethi** [comment]
LGTM :+1: , but can you please rebase your branch to avoid merge conflict?

**Comment by mpclarkson** [comment]
@dethi Done. Should be fine to merge without conflicts now.

**Comment by dethi** [comment]
Thanks! :)

**Pull request merged**
