### PR TITLE
Add swiftLanguageVersions to Package.swift

### PR DESCRIPTION
**Pull request by mackoj**

### CODE REVIEW

**Comment by spinach** [comment]
Hey @mackoj ,

Thanks a lot for submitting this fix. Just to double check, this made it work for you on Xcode 11? 

Cheers

**Comment by quanvo87** [comment]
I tested this and yes it works in Xcode 11. However, you will have to `import AlgoliaSearch` rather than `import InstantSearchClient`.

**Comment by mikeastock** [comment]
When will this get released?

**Comment by spinach** [comment]
Just merged, thanks for reminding me!

**Pull request merged**
