### PR TITLE
tvOS Podspec

### PR DESCRIPTION
**Pull request by JonathanBouaziz**
Hello,

I've added and tested the framework on tvOS and it seems to be working well. Could you merge it?

Thanks!

### CODE REVIEW

**Comment by clement-leprovost** [comment]
Sure! Actually, tvOS is supported since version 3.1 (see #49). There is a tvOS target in our continuous integration tests (see `.travis.yml`). Strange that we didn't update the podspec earlier... Thanks for spotting it. :)

**Comment by JonathanBouaziz** [comment]
Thanks! :)

I forgot to bump the app version though.

**Comment by clement-leprovost** [comment]
@JonathanBouaziz We still need to release the pod, anyway, so we'll bump it then. We usually try to batch updates, so it might take a few days. Can you wait?

**Comment by clement-leprovost** [comment]
@JonathanBouaziz Will do.

**Comment by clement-leprovost** [comment]
Version [3.6](https://github.com/algolia/algoliasearch-client-swift/releases/tag/3.6) has been released, which includes this PR.

**Comment by JonathanBouaziz** [comment]
Thanks for letting me know @clement-leprovost !

**Pull request merged**
